# coding: utf-8

"""
    Portal API

    Portal API provides secure access to contact, job, and file management resources. This API uses bearer token authentication and multi-tenant architecture. 

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@datahubportal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class FileKind(str, Enum):
    """
    File classification types
    """

    """
    allowed enum values
    """
    DOCUMENT = 'document'
    PHOTO = 'photo'
    INVOICE = 'invoice'
    REPORT = 'report'
    OTHER = 'other'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FileKind from a JSON string"""
        return cls(json.loads(json_str))


