# coding: utf-8

"""
    Portal API

    Portal API provides secure access to contact, job, and file management resources. This API uses bearer token authentication and multi-tenant architecture. 

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@datahubportal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from datahub_portal_api.models.file_kind import FileKind
from typing import Optional, Set
from typing_extensions import Self

class FileAsset(BaseModel):
    """
    FileAsset
    """ # noqa: E501
    id: Annotated[str, Field(strict=True)] = Field(description="Unique file identifier")
    name: StrictStr = Field(description="Original filename")
    kind: FileKind
    size: StrictInt = Field(description="File size in bytes")
    mime_type: StrictStr = Field(description="MIME type")
    signed_url: StrictStr = Field(description="Temporary signed URL for file access")
    expires_at: datetime = Field(description="When the signed URL expires (typically 15 minutes)")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Optional file metadata")
    created_at: datetime
    __properties: ClassVar[List[str]] = ["id", "name", "kind", "size", "mime_type", "signed_url", "expires_at", "metadata", "created_at"]

    @field_validator('id')
    def id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^file_[a-z0-9]{8}$", value):
            raise ValueError(r"must validate the regular expression /^file_[a-z0-9]{8}$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FileAsset from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FileAsset from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "kind": obj.get("kind"),
            "size": obj.get("size"),
            "mime_type": obj.get("mime_type"),
            "signed_url": obj.get("signed_url"),
            "expires_at": obj.get("expires_at"),
            "metadata": obj.get("metadata"),
            "created_at": obj.get("created_at")
        })
        return _obj


