# coding: utf-8

"""
    Portal API

    Portal API provides secure access to contact, job, and file management resources. This API uses bearer token authentication and multi-tenant architecture. 

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@datahubportal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from datahub_portal_api.models.job_status import JobStatus
from typing import Optional, Set
from typing_extensions import Self

class Job(BaseModel):
    """
    Job
    """ # noqa: E501
    id: Annotated[str, Field(strict=True)] = Field(description="Unique job identifier")
    title: StrictStr = Field(description="Job title or description")
    status: JobStatus
    status_reason: Optional[StrictStr] = Field(default=None, description="Optional reason for status (especially for blocked)")
    status_updated_at: datetime = Field(description="When status last changed")
    priority: StrictStr
    contact_id: Annotated[str, Field(strict=True)] = Field(description="Associated contact ID")
    scheduled_start: Optional[datetime] = Field(default=None, description="Scheduled start time")
    scheduled_end: Optional[datetime] = Field(default=None, description="Scheduled end time")
    assignee_ids: Optional[List[StrictStr]] = None
    tags: Optional[List[StrictStr]] = None
    created_at: datetime
    updated_at: datetime
    __properties: ClassVar[List[str]] = ["id", "title", "status", "status_reason", "status_updated_at", "priority", "contact_id", "scheduled_start", "scheduled_end", "assignee_ids", "tags", "created_at", "updated_at"]

    @field_validator('id')
    def id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^job_[a-z0-9]{8}$", value):
            raise ValueError(r"must validate the regular expression /^job_[a-z0-9]{8}$/")
        return value

    @field_validator('priority')
    def priority_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['low', 'medium', 'high', 'urgent']):
            raise ValueError("must be one of enum values ('low', 'medium', 'high', 'urgent')")
        return value

    @field_validator('contact_id')
    def contact_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^con_[a-z0-9]{8}$", value):
            raise ValueError(r"must validate the regular expression /^con_[a-z0-9]{8}$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Job from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Job from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "title": obj.get("title"),
            "status": obj.get("status"),
            "status_reason": obj.get("status_reason"),
            "status_updated_at": obj.get("status_updated_at"),
            "priority": obj.get("priority"),
            "contact_id": obj.get("contact_id"),
            "scheduled_start": obj.get("scheduled_start"),
            "scheduled_end": obj.get("scheduled_end"),
            "assignee_ids": obj.get("assignee_ids"),
            "tags": obj.get("tags"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


