name: Feature request
description: Propose an enhancement for docs, spec or mocks
labels: [enhancement]
body:
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: What problem does this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Detail what you would change (pages, endpoints, examples, etc.).
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: How will we know it's done?