# coding: utf-8

"""
    Portal API

    Portal API provides secure access to contact, job, and file management resources. This API uses bearer token authentication and multi-tenant architecture. 

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@datahubportal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from datahub_portal_api.models.job import Job

class TestJob(unittest.TestCase):
    """Job unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Job:
        """Test Job
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Job`
        """
        model = Job()
        if include_optional:
            return Job(
                id = 'job_x1y2z3a4',
                title = 'HVAC Maintenance - Building A',
                status = 'in_progress',
                status_reason = 'Awaiting parts delivery',
                status_updated_at = '2024-01-20T08:00Z',
                priority = 'high',
                contact_id = 'con_a1b2c3d4',
                scheduled_start = '2024-01-20T09:00Z',
                scheduled_end = '2024-01-20T17:00Z',
                assignee_ids = ["usr_abc123","usr_def456"],
                tags = ["maintenance","hvac"],
                created_at = '2024-01-18T14:30Z',
                updated_at = '2024-01-20T08:00Z'
            )
        else:
            return Job(
                id = 'job_x1y2z3a4',
                title = 'HVAC Maintenance - Building A',
                status = 'in_progress',
                status_updated_at = '2024-01-20T08:00Z',
                priority = 'high',
                contact_id = 'con_a1b2c3d4',
                created_at = '2024-01-18T14:30Z',
                updated_at = '2024-01-20T08:00Z',
        )
        """

    def testJob(self):
        """Test Job"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
