# coding: utf-8

"""
    Portal API

    Portal API provides secure access to contact, job, and file management resources. This API uses bearer token authentication and multi-tenant architecture. 

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@datahubportal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from datahub_portal_api.models.error import Error

class TestError(unittest.TestCase):
    """Error unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Error:
        """Test Error
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Error`
        """
        model = Error()
        if include_optional:
            return Error(
                type = 'https://api.portal.example.com/errors/validation',
                title = 'Validation Error',
                status = 422,
                code = 'VALIDATION_FAILED',
                detail = 'The provided email format is invalid',
                trace_id = 'abc123-def456-ghi789',
                errors = [
                    datahub_portal_api.models.validation_error.ValidationError(
                        field = 'email', 
                        message = 'Must be a valid email address', 
                        code = 'format.email', )
                    ]
            )
        else:
            return Error(
                type = 'https://api.portal.example.com/errors/validation',
                title = 'Validation Error',
                status = 422,
                code = 'VALIDATION_FAILED',
                detail = 'The provided email format is invalid',
                trace_id = 'abc123-def456-ghi789',
        )
        """

    def testError(self):
        """Test Error"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
