# coding: utf-8

"""
    Portal API

    Portal API provides secure access to contact, job, and file management resources. This API uses bearer token authentication and multi-tenant architecture. 

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@datahubportal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from datahub_portal_api.models.list_contacts200_response import ListContacts200Response

class TestListContacts200Response(unittest.TestCase):
    """ListContacts200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListContacts200Response:
        """Test ListContacts200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListContacts200Response`
        """
        model = ListContacts200Response()
        if include_optional:
            return ListContacts200Response(
                total = 47,
                limit = 25,
                offset = 0,
                has_more = True,
                data = [
                    datahub_portal_api.models.contact.Contact(
                        id = 'con_a1b2c3d4', 
                        name = 'John Smith', 
                        company = 'Acme Corp', 
                        emails = [
                            datahub_portal_api.models.contact_email.ContactEmail(
                                email = 'john@example.com', 
                                type = 'work', 
                                is_primary = True, )
                            ], 
                        phones = [
                            datahub_portal_api.models.contact_phone.ContactPhone(
                                phone = '+14155551234', 
                                type = 'mobile', 
                                is_primary = True, )
                            ], 
                        address = datahub_portal_api.models.contact_address.Contact_address(
                            street = '123 Main St', 
                            city = 'San Francisco', 
                            state = 'CA', 
                            postal_code = '94105', 
                            country = 'US', ), 
                        tags = ["vip","contractor"], 
                        created_at = '2024-01-15T10:30Z', 
                        updated_at = '2024-01-20T14:45Z', )
                    ]
            )
        else:
            return ListContacts200Response(
                total = 47,
                limit = 25,
                offset = 0,
                has_more = True,
        )
        """

    def testListContacts200Response(self):
        """Test ListContacts200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
