# coding: utf-8

"""
    Portal API

    Portal API provides secure access to contact, job, and file management resources. This API uses bearer token authentication and multi-tenant architecture. 

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@datahubportal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from datahub_portal_api.models.contact_address import ContactAddress

class TestContactAddress(unittest.TestCase):
    """ContactAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContactAddress:
        """Test ContactAddress
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContactAddress`
        """
        model = ContactAddress()
        if include_optional:
            return ContactAddress(
                street = '123 Main St',
                city = 'San Francisco',
                state = 'CA',
                postal_code = '94105',
                country = 'US'
            )
        else:
            return ContactAddress(
        )
        """

    def testContactAddress(self):
        """Test ContactAddress"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
