# coding: utf-8

"""
    Portal API

    Portal API provides secure access to contact, job, and file management resources. This API uses bearer token authentication and multi-tenant architecture. 

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@datahubportal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from datahub_portal_api.models.file_asset import FileAsset

class TestFileAsset(unittest.TestCase):
    """FileAsset unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FileAsset:
        """Test FileAsset
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FileAsset`
        """
        model = FileAsset()
        if include_optional:
            return FileAsset(
                id = 'file_m3n4o5p6',
                name = 'site_photo_001.jpg',
                kind = 'photo',
                size = 2457600,
                mime_type = 'image/jpeg',
                signed_url = 'https://storage.example.com/files/abc123?token=xyz&expires=1705745400',
                expires_at = '2024-01-20T10:30Z',
                metadata = { },
                created_at = '2024-01-20T10:15Z'
            )
        else:
            return FileAsset(
                id = 'file_m3n4o5p6',
                name = 'site_photo_001.jpg',
                kind = 'photo',
                size = 2457600,
                mime_type = 'image/jpeg',
                signed_url = 'https://storage.example.com/files/abc123?token=xyz&expires=1705745400',
                expires_at = '2024-01-20T10:30Z',
                created_at = '2024-01-20T10:15Z',
        )
        """

    def testFileAsset(self):
        """Test FileAsset"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
