# coding: utf-8

"""
    Portal API

    Portal API provides secure access to contact, job, and file management resources. This API uses bearer token authentication and multi-tenant architecture. 

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@datahubportal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from datahub_portal_api.models.file_kind import FileKind

class TestFileKind(unittest.TestCase):
    """FileKind unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFileKind(self):
        """Test FileKind"""
        # inst = FileKind()

if __name__ == '__main__':
    unittest.main()
