# coding: utf-8

"""
    Portal API

    Portal API provides secure access to contact, job, and file management resources. This API uses bearer token authentication and multi-tenant architecture. 

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@datahubportal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from datahub_portal_api.models.contact import Contact

class TestContact(unittest.TestCase):
    """Contact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Contact:
        """Test Contact
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Contact`
        """
        model = Contact()
        if include_optional:
            return Contact(
                id = 'con_a1b2c3d4',
                name = 'John Smith',
                company = 'Acme Corp',
                emails = [
                    datahub_portal_api.models.contact_email.ContactEmail(
                        email = 'john@example.com', 
                        type = 'work', 
                        is_primary = True, )
                    ],
                phones = [
                    datahub_portal_api.models.contact_phone.ContactPhone(
                        phone = '+14155551234', 
                        type = 'mobile', 
                        is_primary = True, )
                    ],
                address = datahub_portal_api.models.contact_address.Contact_address(
                    street = '123 Main St', 
                    city = 'San Francisco', 
                    state = 'CA', 
                    postal_code = '94105', 
                    country = 'US', ),
                tags = ["vip","contractor"],
                created_at = '2024-01-15T10:30Z',
                updated_at = '2024-01-20T14:45Z'
            )
        else:
            return Contact(
                id = 'con_a1b2c3d4',
                name = 'John Smith',
                emails = [
                    datahub_portal_api.models.contact_email.ContactEmail(
                        email = 'john@example.com', 
                        type = 'work', 
                        is_primary = True, )
                    ],
                created_at = '2024-01-15T10:30Z',
                updated_at = '2024-01-20T14:45Z',
        )
        """

    def testContact(self):
        """Test Contact"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
