/* tslint:disable */
/* eslint-disable */
/**
 * Portal API
 * Portal API provides secure access to contact, job, and file management resources. This API uses bearer token authentication and multi-tenant architecture. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@datahubportal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContactPhone
 */
export interface ContactPhone {
    /**
     * E.164 format
     * @type {string}
     * @memberof ContactPhone
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof ContactPhone
     */
    type: ContactPhoneTypeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof ContactPhone
     */
    isPrimary: boolean;
}


/**
 * @export
 */
export const ContactPhoneTypeEnum = {
    Mobile: 'mobile',
    Work: 'work',
    Home: 'home',
    Other: 'other'
} as const;
export type ContactPhoneTypeEnum = typeof ContactPhoneTypeEnum[keyof typeof ContactPhoneTypeEnum];


/**
 * Check if a given object implements the ContactPhone interface.
 */
export function instanceOfContactPhone(value: object): value is ContactPhone {
    if (!('phone' in value) || value['phone'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('isPrimary' in value) || value['isPrimary'] === undefined) return false;
    return true;
}

export function ContactPhoneFromJSON(json: any): ContactPhone {
    return ContactPhoneFromJSONTyped(json, false);
}

export function ContactPhoneFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactPhone {
    if (json == null) {
        return json;
    }
    return {
        
        'phone': json['phone'],
        'type': json['type'],
        'isPrimary': json['is_primary'],
    };
}

export function ContactPhoneToJSON(json: any): ContactPhone {
    return ContactPhoneToJSONTyped(json, false);
}

export function ContactPhoneToJSONTyped(value?: ContactPhone | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'phone': value['phone'],
        'type': value['type'],
        'is_primary': value['isPrimary'],
    };
}

