/* tslint:disable */
/* eslint-disable */
/**
 * Portal API
 * Portal API provides secure access to contact, job, and file management resources. This API uses bearer token authentication and multi-tenant architecture. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@datahubportal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContactAddress
 */
export interface ContactAddress {
    /**
     * 
     * @type {string}
     * @memberof ContactAddress
     */
    street?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactAddress
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactAddress
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactAddress
     */
    postalCode?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactAddress
     */
    country?: string;
}

/**
 * Check if a given object implements the ContactAddress interface.
 */
export function instanceOfContactAddress(value: object): value is ContactAddress {
    return true;
}

export function ContactAddressFromJSON(json: any): ContactAddress {
    return ContactAddressFromJSONTyped(json, false);
}

export function ContactAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactAddress {
    if (json == null) {
        return json;
    }
    return {
        
        'street': json['street'] == null ? undefined : json['street'],
        'city': json['city'] == null ? undefined : json['city'],
        'state': json['state'] == null ? undefined : json['state'],
        'postalCode': json['postal_code'] == null ? undefined : json['postal_code'],
        'country': json['country'] == null ? undefined : json['country'],
    };
}

export function ContactAddressToJSON(json: any): ContactAddress {
    return ContactAddressToJSONTyped(json, false);
}

export function ContactAddressToJSONTyped(value?: ContactAddress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'street': value['street'],
        'city': value['city'],
        'state': value['state'],
        'postal_code': value['postalCode'],
        'country': value['country'],
    };
}

