/* tslint:disable */
/* eslint-disable */
/**
 * Portal API
 * Portal API provides secure access to contact, job, and file management resources. This API uses bearer token authentication and multi-tenant architecture. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@datahubportal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContactEmail
 */
export interface ContactEmail {
    /**
     * 
     * @type {string}
     * @memberof ContactEmail
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof ContactEmail
     */
    type: ContactEmailTypeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof ContactEmail
     */
    isPrimary: boolean;
}


/**
 * @export
 */
export const ContactEmailTypeEnum = {
    Work: 'work',
    Personal: 'personal',
    Other: 'other'
} as const;
export type ContactEmailTypeEnum = typeof ContactEmailTypeEnum[keyof typeof ContactEmailTypeEnum];


/**
 * Check if a given object implements the ContactEmail interface.
 */
export function instanceOfContactEmail(value: object): value is ContactEmail {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('isPrimary' in value) || value['isPrimary'] === undefined) return false;
    return true;
}

export function ContactEmailFromJSON(json: any): ContactEmail {
    return ContactEmailFromJSONTyped(json, false);
}

export function ContactEmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactEmail {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'type': json['type'],
        'isPrimary': json['is_primary'],
    };
}

export function ContactEmailToJSON(json: any): ContactEmail {
    return ContactEmailToJSONTyped(json, false);
}

export function ContactEmailToJSONTyped(value?: ContactEmail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'type': value['type'],
        'is_primary': value['isPrimary'],
    };
}

