/* tslint:disable */
/* eslint-disable */
/**
 * Portal API
 * Portal API provides secure access to contact, job, and file management resources. This API uses bearer token authentication and multi-tenant architecture. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@datahubportal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContactAddress } from './ContactAddress';
import {
    ContactAddressFromJSON,
    ContactAddressFromJSONTyped,
    ContactAddressToJSON,
    ContactAddressToJSONTyped,
} from './ContactAddress';
import type { ContactPhone } from './ContactPhone';
import {
    ContactPhoneFromJSON,
    ContactPhoneFromJSONTyped,
    ContactPhoneToJSON,
    ContactPhoneToJSONTyped,
} from './ContactPhone';
import type { ContactEmail } from './ContactEmail';
import {
    ContactEmailFromJSON,
    ContactEmailFromJSONTyped,
    ContactEmailToJSON,
    ContactEmailToJSONTyped,
} from './ContactEmail';

/**
 * 
 * @export
 * @interface Contact
 */
export interface Contact {
    /**
     * Unique contact identifier
     * @type {string}
     * @memberof Contact
     */
    id: string;
    /**
     * Full name of the contact
     * @type {string}
     * @memberof Contact
     */
    name: string;
    /**
     * Company or organization name
     * @type {string}
     * @memberof Contact
     */
    company?: string;
    /**
     * 
     * @type {Array<ContactEmail>}
     * @memberof Contact
     */
    emails: Array<ContactEmail>;
    /**
     * 
     * @type {Array<ContactPhone>}
     * @memberof Contact
     */
    phones?: Array<ContactPhone>;
    /**
     * 
     * @type {ContactAddress}
     * @memberof Contact
     */
    address?: ContactAddress;
    /**
     * 
     * @type {Array<string>}
     * @memberof Contact
     */
    tags?: Array<string>;
    /**
     * ISO 8601 timestamp
     * @type {Date}
     * @memberof Contact
     */
    createdAt: Date;
    /**
     * ISO 8601 timestamp
     * @type {Date}
     * @memberof Contact
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the Contact interface.
 */
export function instanceOfContact(value: object): value is Contact {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('emails' in value) || value['emails'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ContactFromJSON(json: any): Contact {
    return ContactFromJSONTyped(json, false);
}

export function ContactFromJSONTyped(json: any, ignoreDiscriminator: boolean): Contact {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'company': json['company'] == null ? undefined : json['company'],
        'emails': ((json['emails'] as Array<any>).map(ContactEmailFromJSON)),
        'phones': json['phones'] == null ? undefined : ((json['phones'] as Array<any>).map(ContactPhoneFromJSON)),
        'address': json['address'] == null ? undefined : ContactAddressFromJSON(json['address']),
        'tags': json['tags'] == null ? undefined : json['tags'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function ContactToJSON(json: any): Contact {
    return ContactToJSONTyped(json, false);
}

export function ContactToJSONTyped(value?: Contact | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'company': value['company'],
        'emails': ((value['emails'] as Array<any>).map(ContactEmailToJSON)),
        'phones': value['phones'] == null ? undefined : ((value['phones'] as Array<any>).map(ContactPhoneToJSON)),
        'address': ContactAddressToJSON(value['address']),
        'tags': value['tags'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
    };
}

