/* tslint:disable */
/* eslint-disable */
/**
 * Portal API
 * Portal API provides secure access to contact, job, and file management resources. This API uses bearer token authentication and multi-tenant architecture. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@datahubportal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileKind } from './FileKind';
import {
    FileKindFromJSON,
    FileKindFromJSONTyped,
    FileKindToJSON,
    FileKindToJSONTyped,
} from './FileKind';

/**
 * 
 * @export
 * @interface FileAsset
 */
export interface FileAsset {
    /**
     * Unique file identifier
     * @type {string}
     * @memberof FileAsset
     */
    id: string;
    /**
     * Original filename
     * @type {string}
     * @memberof FileAsset
     */
    name: string;
    /**
     * 
     * @type {FileKind}
     * @memberof FileAsset
     */
    kind: FileKind;
    /**
     * File size in bytes
     * @type {number}
     * @memberof FileAsset
     */
    size: number;
    /**
     * MIME type
     * @type {string}
     * @memberof FileAsset
     */
    mimeType: string;
    /**
     * Temporary signed URL for file access
     * @type {string}
     * @memberof FileAsset
     */
    signedUrl: string;
    /**
     * When the signed URL expires (typically 15 minutes)
     * @type {Date}
     * @memberof FileAsset
     */
    expiresAt: Date;
    /**
     * Optional file metadata
     * @type {{ [key: string]: any; }}
     * @memberof FileAsset
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     * @type {Date}
     * @memberof FileAsset
     */
    createdAt: Date;
}



/**
 * Check if a given object implements the FileAsset interface.
 */
export function instanceOfFileAsset(value: object): value is FileAsset {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('mimeType' in value) || value['mimeType'] === undefined) return false;
    if (!('signedUrl' in value) || value['signedUrl'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function FileAssetFromJSON(json: any): FileAsset {
    return FileAssetFromJSONTyped(json, false);
}

export function FileAssetFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileAsset {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'kind': FileKindFromJSON(json['kind']),
        'size': json['size'],
        'mimeType': json['mime_type'],
        'signedUrl': json['signed_url'],
        'expiresAt': (new Date(json['expires_at'])),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function FileAssetToJSON(json: any): FileAsset {
    return FileAssetToJSONTyped(json, false);
}

export function FileAssetToJSONTyped(value?: FileAsset | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'kind': FileKindToJSON(value['kind']),
        'size': value['size'],
        'mime_type': value['mimeType'],
        'signed_url': value['signedUrl'],
        'expires_at': ((value['expiresAt']).toISOString()),
        'metadata': value['metadata'],
        'created_at': ((value['createdAt']).toISOString()),
    };
}

