/* tslint:disable */
/* eslint-disable */
/**
 * Portal API
 * Portal API provides secure access to contact, job, and file management resources. This API uses bearer token authentication and multi-tenant architecture. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@datahubportal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * File classification types
 * @export
 */
export const FileKind = {
    Document: 'document',
    Photo: 'photo',
    Invoice: 'invoice',
    Report: 'report',
    Other: 'other'
} as const;
export type FileKind = typeof FileKind[keyof typeof FileKind];


export function instanceOfFileKind(value: any): boolean {
    for (const key in FileKind) {
        if (Object.prototype.hasOwnProperty.call(FileKind, key)) {
            if (FileKind[key as keyof typeof FileKind] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FileKindFromJSON(json: any): FileKind {
    return FileKindFromJSONTyped(json, false);
}

export function FileKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileKind {
    return json as FileKind;
}

export function FileKindToJSON(value?: FileKind | null): any {
    return value as any;
}

export function FileKindToJSONTyped(value: any, ignoreDiscriminator: boolean): FileKind {
    return value as FileKind;
}

