/* tslint:disable */
/* eslint-disable */
/**
 * Portal API
 * Portal API provides secure access to contact, job, and file management resources. This API uses bearer token authentication and multi-tenant architecture. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@datahubportal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileAsset } from './FileAsset';
import {
    FileAssetFromJSON,
    FileAssetFromJSONTyped,
    FileAssetToJSON,
    FileAssetToJSONTyped,
} from './FileAsset';

/**
 * 
 * @export
 * @interface GetJobFiles200Response
 */
export interface GetJobFiles200Response {
    /**
     * Total number of items available
     * @type {number}
     * @memberof GetJobFiles200Response
     */
    total: number;
    /**
     * Maximum items returned
     * @type {number}
     * @memberof GetJobFiles200Response
     */
    limit: number;
    /**
     * Number of items skipped
     * @type {number}
     * @memberof GetJobFiles200Response
     */
    offset: number;
    /**
     * Whether more items exist
     * @type {boolean}
     * @memberof GetJobFiles200Response
     */
    hasMore: boolean;
    /**
     * 
     * @type {Array<FileAsset>}
     * @memberof GetJobFiles200Response
     */
    data?: Array<FileAsset>;
}

/**
 * Check if a given object implements the GetJobFiles200Response interface.
 */
export function instanceOfGetJobFiles200Response(value: object): value is GetJobFiles200Response {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function GetJobFiles200ResponseFromJSON(json: any): GetJobFiles200Response {
    return GetJobFiles200ResponseFromJSONTyped(json, false);
}

export function GetJobFiles200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetJobFiles200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'limit': json['limit'],
        'offset': json['offset'],
        'hasMore': json['has_more'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(FileAssetFromJSON)),
    };
}

export function GetJobFiles200ResponseToJSON(json: any): GetJobFiles200Response {
    return GetJobFiles200ResponseToJSONTyped(json, false);
}

export function GetJobFiles200ResponseToJSONTyped(value?: GetJobFiles200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'limit': value['limit'],
        'offset': value['offset'],
        'has_more': value['hasMore'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(FileAssetToJSON)),
    };
}

