/* tslint:disable */
/* eslint-disable */
/**
 * Portal API
 * Portal API provides secure access to contact, job, and file management resources. This API uses bearer token authentication and multi-tenant architecture. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@datahubportal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobStatus } from './JobStatus';
import {
    JobStatusFromJSON,
    JobStatusFromJSONTyped,
    JobStatusToJSON,
    JobStatusToJSONTyped,
} from './JobStatus';

/**
 * 
 * @export
 * @interface Job
 */
export interface Job {
    /**
     * Unique job identifier
     * @type {string}
     * @memberof Job
     */
    id: string;
    /**
     * Job title or description
     * @type {string}
     * @memberof Job
     */
    title: string;
    /**
     * 
     * @type {JobStatus}
     * @memberof Job
     */
    status: JobStatus;
    /**
     * Optional reason for status (especially for blocked)
     * @type {string}
     * @memberof Job
     */
    statusReason?: string;
    /**
     * When status last changed
     * @type {Date}
     * @memberof Job
     */
    statusUpdatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    priority: JobPriorityEnum;
    /**
     * Associated contact ID
     * @type {string}
     * @memberof Job
     */
    contactId: string;
    /**
     * Scheduled start time
     * @type {Date}
     * @memberof Job
     */
    scheduledStart?: Date;
    /**
     * Scheduled end time
     * @type {Date}
     * @memberof Job
     */
    scheduledEnd?: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof Job
     */
    assigneeIds?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Job
     */
    tags?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof Job
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Job
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const JobPriorityEnum = {
    Low: 'low',
    Medium: 'medium',
    High: 'high',
    Urgent: 'urgent'
} as const;
export type JobPriorityEnum = typeof JobPriorityEnum[keyof typeof JobPriorityEnum];


/**
 * Check if a given object implements the Job interface.
 */
export function instanceOfJob(value: object): value is Job {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('statusUpdatedAt' in value) || value['statusUpdatedAt'] === undefined) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    if (!('contactId' in value) || value['contactId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function JobFromJSON(json: any): Job {
    return JobFromJSONTyped(json, false);
}

export function JobFromJSONTyped(json: any, ignoreDiscriminator: boolean): Job {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'status': JobStatusFromJSON(json['status']),
        'statusReason': json['status_reason'] == null ? undefined : json['status_reason'],
        'statusUpdatedAt': (new Date(json['status_updated_at'])),
        'priority': json['priority'],
        'contactId': json['contact_id'],
        'scheduledStart': json['scheduled_start'] == null ? undefined : (new Date(json['scheduled_start'])),
        'scheduledEnd': json['scheduled_end'] == null ? undefined : (new Date(json['scheduled_end'])),
        'assigneeIds': json['assignee_ids'] == null ? undefined : json['assignee_ids'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function JobToJSON(json: any): Job {
    return JobToJSONTyped(json, false);
}

export function JobToJSONTyped(value?: Job | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'status': JobStatusToJSON(value['status']),
        'status_reason': value['statusReason'],
        'status_updated_at': ((value['statusUpdatedAt']).toISOString()),
        'priority': value['priority'],
        'contact_id': value['contactId'],
        'scheduled_start': value['scheduledStart'] == null ? undefined : ((value['scheduledStart']).toISOString()),
        'scheduled_end': value['scheduledEnd'] == null ? undefined : ((value['scheduledEnd']).toISOString()),
        'assignee_ids': value['assigneeIds'],
        'tags': value['tags'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
    };
}

