/* tslint:disable */
/* eslint-disable */
/**
 * Portal API
 * Portal API provides secure access to contact, job, and file management resources. This API uses bearer token authentication and multi-tenant architecture. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@datahubportal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Canonical job status values
 * @export
 */
export const JobStatus = {
    Open: 'open',
    Scheduled: 'scheduled',
    InProgress: 'in_progress',
    Blocked: 'blocked',
    AwaitingReview: 'awaiting_review',
    Completed: 'completed',
    Canceled: 'canceled',
    Archived: 'archived'
} as const;
export type JobStatus = typeof JobStatus[keyof typeof JobStatus];


export function instanceOfJobStatus(value: any): boolean {
    for (const key in JobStatus) {
        if (Object.prototype.hasOwnProperty.call(JobStatus, key)) {
            if (JobStatus[key as keyof typeof JobStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function JobStatusFromJSON(json: any): JobStatus {
    return JobStatusFromJSONTyped(json, false);
}

export function JobStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobStatus {
    return json as JobStatus;
}

export function JobStatusToJSON(value?: JobStatus | null): any {
    return value as any;
}

export function JobStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): JobStatus {
    return value as JobStatus;
}

