/* tslint:disable */
/* eslint-disable */
/**
 * Portal API
 * Portal API provides secure access to contact, job, and file management resources. This API uses bearer token authentication and multi-tenant architecture. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@datahubportal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Job } from './Job';
import {
    JobFromJSON,
    JobFromJSONTyped,
    JobToJSON,
    JobToJSONTyped,
} from './Job';

/**
 * 
 * @export
 * @interface ListJobs200Response
 */
export interface ListJobs200Response {
    /**
     * Total number of items available
     * @type {number}
     * @memberof ListJobs200Response
     */
    total: number;
    /**
     * Maximum items returned
     * @type {number}
     * @memberof ListJobs200Response
     */
    limit: number;
    /**
     * Number of items skipped
     * @type {number}
     * @memberof ListJobs200Response
     */
    offset: number;
    /**
     * Whether more items exist
     * @type {boolean}
     * @memberof ListJobs200Response
     */
    hasMore: boolean;
    /**
     * 
     * @type {Array<Job>}
     * @memberof ListJobs200Response
     */
    data?: Array<Job>;
}

/**
 * Check if a given object implements the ListJobs200Response interface.
 */
export function instanceOfListJobs200Response(value: object): value is ListJobs200Response {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function ListJobs200ResponseFromJSON(json: any): ListJobs200Response {
    return ListJobs200ResponseFromJSONTyped(json, false);
}

export function ListJobs200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListJobs200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'limit': json['limit'],
        'offset': json['offset'],
        'hasMore': json['has_more'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(JobFromJSON)),
    };
}

export function ListJobs200ResponseToJSON(json: any): ListJobs200Response {
    return ListJobs200ResponseToJSONTyped(json, false);
}

export function ListJobs200ResponseToJSONTyped(value?: ListJobs200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'limit': value['limit'],
        'offset': value['offset'],
        'has_more': value['hasMore'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(JobToJSON)),
    };
}

