/* tslint:disable */
/* eslint-disable */
/**
 * Portal API
 * Portal API provides secure access to contact, job, and file management resources. This API uses bearer token authentication and multi-tenant architecture. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@datahubportal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Contact } from './Contact';
import {
    ContactFromJSON,
    ContactFromJSONTyped,
    ContactToJSON,
    ContactToJSONTyped,
} from './Contact';

/**
 * 
 * @export
 * @interface ListContacts200Response
 */
export interface ListContacts200Response {
    /**
     * Total number of items available
     * @type {number}
     * @memberof ListContacts200Response
     */
    total: number;
    /**
     * Maximum items returned
     * @type {number}
     * @memberof ListContacts200Response
     */
    limit: number;
    /**
     * Number of items skipped
     * @type {number}
     * @memberof ListContacts200Response
     */
    offset: number;
    /**
     * Whether more items exist
     * @type {boolean}
     * @memberof ListContacts200Response
     */
    hasMore: boolean;
    /**
     * 
     * @type {Array<Contact>}
     * @memberof ListContacts200Response
     */
    data?: Array<Contact>;
}

/**
 * Check if a given object implements the ListContacts200Response interface.
 */
export function instanceOfListContacts200Response(value: object): value is ListContacts200Response {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function ListContacts200ResponseFromJSON(json: any): ListContacts200Response {
    return ListContacts200ResponseFromJSONTyped(json, false);
}

export function ListContacts200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListContacts200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'limit': json['limit'],
        'offset': json['offset'],
        'hasMore': json['has_more'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ContactFromJSON)),
    };
}

export function ListContacts200ResponseToJSON(json: any): ListContacts200Response {
    return ListContacts200ResponseToJSONTyped(json, false);
}

export function ListContacts200ResponseToJSONTyped(value?: ListContacts200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'limit': value['limit'],
        'offset': value['offset'],
        'has_more': value['hasMore'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ContactToJSON)),
    };
}

