/* tslint:disable */
/* eslint-disable */
/**
 * Portal API
 * Portal API provides secure access to contact, job, and file management resources. This API uses bearer token authentication and multi-tenant architecture. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@datahubportal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ValidationError } from './ValidationError';
import {
    ValidationErrorFromJSON,
    ValidationErrorFromJSONTyped,
    ValidationErrorToJSON,
    ValidationErrorToJSONTyped,
} from './ValidationError';

/**
 * 
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * URI reference for error type
     * @type {string}
     * @memberof ModelError
     */
    type: string;
    /**
     * Short error description
     * @type {string}
     * @memberof ModelError
     */
    title: string;
    /**
     * HTTP status code
     * @type {number}
     * @memberof ModelError
     */
    status: number;
    /**
     * Application-specific error code
     * @type {string}
     * @memberof ModelError
     */
    code: string;
    /**
     * Detailed error message
     * @type {string}
     * @memberof ModelError
     */
    detail: string;
    /**
     * Request trace identifier for debugging
     * @type {string}
     * @memberof ModelError
     */
    traceId: string;
    /**
     * Field-specific validation errors
     * @type {Array<ValidationError>}
     * @memberof ModelError
     */
    errors?: Array<ValidationError>;
}

/**
 * Check if a given object implements the ModelError interface.
 */
export function instanceOfModelError(value: object): value is ModelError {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('detail' in value) || value['detail'] === undefined) return false;
    if (!('traceId' in value) || value['traceId'] === undefined) return false;
    return true;
}

export function ModelErrorFromJSON(json: any): ModelError {
    return ModelErrorFromJSONTyped(json, false);
}

export function ModelErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelError {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'title': json['title'],
        'status': json['status'],
        'code': json['code'],
        'detail': json['detail'],
        'traceId': json['traceId'],
        'errors': json['errors'] == null ? undefined : ((json['errors'] as Array<any>).map(ValidationErrorFromJSON)),
    };
}

export function ModelErrorToJSON(json: any): ModelError {
    return ModelErrorToJSONTyped(json, false);
}

export function ModelErrorToJSONTyped(value?: ModelError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'title': value['title'],
        'status': value['status'],
        'code': value['code'],
        'detail': value['detail'],
        'traceId': value['traceId'],
        'errors': value['errors'] == null ? undefined : ((value['errors'] as Array<any>).map(ValidationErrorToJSON)),
    };
}

