/* tslint:disable */
/* eslint-disable */
/**
 * Portal API
 * Portal API provides secure access to contact, job, and file management resources. This API uses bearer token authentication and multi-tenant architecture. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@datahubportal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginationResponse
 */
export interface PaginationResponse {
    /**
     * Total number of items available
     * @type {number}
     * @memberof PaginationResponse
     */
    total: number;
    /**
     * Maximum items returned
     * @type {number}
     * @memberof PaginationResponse
     */
    limit: number;
    /**
     * Number of items skipped
     * @type {number}
     * @memberof PaginationResponse
     */
    offset: number;
    /**
     * Whether more items exist
     * @type {boolean}
     * @memberof PaginationResponse
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the PaginationResponse interface.
 */
export function instanceOfPaginationResponse(value: object): value is PaginationResponse {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function PaginationResponseFromJSON(json: any): PaginationResponse {
    return PaginationResponseFromJSONTyped(json, false);
}

export function PaginationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'limit': json['limit'],
        'offset': json['offset'],
        'hasMore': json['has_more'],
    };
}

export function PaginationResponseToJSON(json: any): PaginationResponse {
    return PaginationResponseToJSONTyped(json, false);
}

export function PaginationResponseToJSONTyped(value?: PaginationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'limit': value['limit'],
        'offset': value['offset'],
        'has_more': value['hasMore'],
    };
}

