/* tslint:disable */
/* eslint-disable */
/**
 * Portal API
 * Portal API provides secure access to contact, job, and file management resources. This API uses bearer token authentication and multi-tenant architecture. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@datahubportal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
    /**
     * Field name that failed validation
     * @type {string}
     * @memberof ValidationError
     */
    field: string;
    /**
     * Validation error message
     * @type {string}
     * @memberof ValidationError
     */
    message: string;
    /**
     * Validation rule that failed
     * @type {string}
     * @memberof ValidationError
     */
    code?: string;
}

/**
 * Check if a given object implements the ValidationError interface.
 */
export function instanceOfValidationError(value: object): value is ValidationError {
    if (!('field' in value) || value['field'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ValidationErrorFromJSON(json: any): ValidationError {
    return ValidationErrorFromJSONTyped(json, false);
}

export function ValidationErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationError {
    if (json == null) {
        return json;
    }
    return {
        
        'field': json['field'],
        'message': json['message'],
        'code': json['code'] == null ? undefined : json['code'],
    };
}

export function ValidationErrorToJSON(json: any): ValidationError {
    return ValidationErrorToJSONTyped(json, false);
}

export function ValidationErrorToJSONTyped(value?: ValidationError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'field': value['field'],
        'message': value['message'],
        'code': value['code'],
    };
}

