/* tslint:disable */
/* eslint-disable */
/**
 * Portal API
 * Portal API provides secure access to contact, job, and file management resources. This API uses bearer token authentication and multi-tenant architecture. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@datahubportal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Contact,
  ListContacts200Response,
} from '../models/index';
import {
    ContactFromJSON,
    ContactToJSON,
    ListContacts200ResponseFromJSON,
    ListContacts200ResponseToJSON,
} from '../models/index';

export interface GetContactByIdRequest {
    id: string;
}

export interface ListContactsRequest {
    limit?: number;
    offset?: number;
    sort?: ListContactsSortEnum;
    dir?: ListContactsDirEnum;
    q?: string;
}

/**
 * 
 */
export class ContactsApi extends runtime.BaseAPI {

    /**
     * Returns a single contact by its unique identifier
     * Get contact by ID
     */
    async getContactByIdRaw(requestParameters: GetContactByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Contact>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getContactById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/contacts/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ContactFromJSON(jsonValue));
    }

    /**
     * Returns a single contact by its unique identifier
     * Get contact by ID
     */
    async getContactById(requestParameters: GetContactByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Contact> {
        const response = await this.getContactByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a paginated list of contacts for the authenticated tenant
     * List contacts
     */
    async listContactsRaw(requestParameters: ListContactsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListContacts200Response>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['dir'] != null) {
            queryParameters['dir'] = requestParameters['dir'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/contacts`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListContacts200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns a paginated list of contacts for the authenticated tenant
     * List contacts
     */
    async listContacts(requestParameters: ListContactsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListContacts200Response> {
        const response = await this.listContactsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListContactsSortEnum = {
    CreatedAt: 'created_at',
    UpdatedAt: 'updated_at',
    Name: 'name',
    Status: 'status',
    Priority: 'priority'
} as const;
export type ListContactsSortEnum = typeof ListContactsSortEnum[keyof typeof ListContactsSortEnum];
/**
 * @export
 */
export const ListContactsDirEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListContactsDirEnum = typeof ListContactsDirEnum[keyof typeof ListContactsDirEnum];
