/* tslint:disable */
/* eslint-disable */
/**
 * Portal API
 * Portal API provides secure access to contact, job, and file management resources. This API uses bearer token authentication and multi-tenant architecture. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@datahubportal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetJobFiles200Response,
} from '../models/index';
import {
    GetJobFiles200ResponseFromJSON,
    GetJobFiles200ResponseToJSON,
} from '../models/index';

export interface GetJobFilesRequest {
    jobId: string;
    limit?: number;
    offset?: number;
    kind?: GetJobFilesKindEnum;
}

/**
 * 
 */
export class FilesApi extends runtime.BaseAPI {

    /**
     * Returns files associated with a job, including signed URLs for access
     * Get job files
     */
    async getJobFilesRaw(requestParameters: GetJobFilesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetJobFiles200Response>> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling getJobFiles().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['kind'] != null) {
            queryParameters['kind'] = requestParameters['kind'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/jobs/{jobId}/files`;
        urlPath = urlPath.replace(`{${"jobId"}}`, encodeURIComponent(String(requestParameters['jobId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetJobFiles200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns files associated with a job, including signed URLs for access
     * Get job files
     */
    async getJobFiles(requestParameters: GetJobFilesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetJobFiles200Response> {
        const response = await this.getJobFilesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetJobFilesKindEnum = {
    Document: 'document',
    Photo: 'photo',
    Invoice: 'invoice',
    Report: 'report',
    Other: 'other'
} as const;
export type GetJobFilesKindEnum = typeof GetJobFilesKindEnum[keyof typeof GetJobFilesKindEnum];
