/* tslint:disable */
/* eslint-disable */
/**
 * Portal API
 * Portal API provides secure access to contact, job, and file management resources. This API uses bearer token authentication and multi-tenant architecture. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@datahubportal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ListJobs200Response,
} from '../models/index';
import {
    ListJobs200ResponseFromJSON,
    ListJobs200ResponseToJSON,
} from '../models/index';

export interface ListJobsRequest {
    limit?: number;
    offset?: number;
    sort?: ListJobsSortEnum;
    dir?: ListJobsDirEnum;
    q?: string;
    status?: ListJobsStatusEnum;
}

/**
 * 
 */
export class JobsApi extends runtime.BaseAPI {

    /**
     * Returns a paginated list of jobs with optional status filtering
     * List jobs
     */
    async listJobsRaw(requestParameters: ListJobsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListJobs200Response>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['dir'] != null) {
            queryParameters['dir'] = requestParameters['dir'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/jobs`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListJobs200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns a paginated list of jobs with optional status filtering
     * List jobs
     */
    async listJobs(requestParameters: ListJobsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListJobs200Response> {
        const response = await this.listJobsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListJobsSortEnum = {
    CreatedAt: 'created_at',
    UpdatedAt: 'updated_at',
    Name: 'name',
    Status: 'status',
    Priority: 'priority'
} as const;
export type ListJobsSortEnum = typeof ListJobsSortEnum[keyof typeof ListJobsSortEnum];
/**
 * @export
 */
export const ListJobsDirEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListJobsDirEnum = typeof ListJobsDirEnum[keyof typeof ListJobsDirEnum];
/**
 * @export
 */
export const ListJobsStatusEnum = {
    Open: 'open',
    Scheduled: 'scheduled',
    InProgress: 'in_progress',
    Blocked: 'blocked',
    AwaitingReview: 'awaiting_review',
    Completed: 'completed',
    Canceled: 'canceled',
    Archived: 'archived'
} as const;
export type ListJobsStatusEnum = typeof ListJobsStatusEnum[keyof typeof ListJobsStatusEnum];
