name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_production:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Build and Deploy Production Docs
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Prepare documentation
        run: |
          # Copy OpenAPI spec to root for easy access
          cp docs/openapi.yaml ./ || echo "OpenAPI spec not found, continuing..."
          
      - name: Deploy to Azure Static Web Apps (Production)
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROD }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "/"
          api_location: ""
          
  build_and_deploy_staging:
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    name: Build and Deploy Staging Docs
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Prepare staging documentation  
        run: |
          # Copy OpenAPI spec and staging robots.txt
          cp docs/openapi.yaml ./ || echo "OpenAPI spec not found, continuing..."
          cp staging/robots.txt ./ || echo "Staging robots.txt not found, using default..."
          
      - name: Deploy to Azure Static Web Apps (Staging)
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_STAGING }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "/"
          api_location: ""

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROD }}
          action: "close"